// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ryprpdyvatkqzzhbwgmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5cHJwZHl2YXRrcXp6aGJ3Z21iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMjYyOTgsImV4cCI6MjA2MzYwMjI5OH0.azbcjoEvK36EoZvgprjqNORUcwCf-ggzTHU13Dgcdh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);